language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t muzammilsayyed2606/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true muzammilsayyed2606/react-test npm test

after_success: 
  - docker build -t muzammilsayyed2606/multi-client ./client
  - docker build -t muzammilsayyed2606/multi-nginx ./nginx
  - docker build -t muzammilsayyed2606/multi-server ./server
  - docker build -t muzammilsayyed2606/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push muzammilsayyed2606/multi-client
  - docker push muzammilsayyed2606/multi-nginx
  - docker push muzammilsayyed2606/multi-server
  - docker push muzammilsayyed2606/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-119556621840'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY